# Generated by Django 5.1.1 on 2025-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefenderMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=20)),
                ("matchday", models.IntegerField()),
                ("teams", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=10)),
                ("minutes", models.IntegerField()),
                ("recoveries", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("goals_conceded", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ForwardMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=20)),
                ("matchday", models.IntegerField()),
                ("teams", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=10)),
                ("minutes", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("shots_on_goal", models.IntegerField()),
                ("dribbles", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GoalkeeperMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=20)),
                ("matchday", models.IntegerField()),
                ("teams", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=10)),
                ("minutes", models.IntegerField()),
                ("saves", models.IntegerField()),
                ("goals_conceded", models.IntegerField()),
                ("errors_leading_to_goal", models.IntegerField()),
                ("penalties_saved", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MidfielderMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=20)),
                ("matchday", models.IntegerField()),
                ("teams", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=10)),
                ("minutes", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("key_passes", models.IntegerField()),
                ("recoveries", models.IntegerField()),
            ],
        ),
    ]
